/* Main.c file generated by New Project wizard
 *
 * Created:   sáb. feb. 5 2022
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
