/* Main.c file generated by New Project wizard
 *
 * Created:   sáb. feb. 5 2022
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include "main.h"

int main (void)
 { 
   RCC->APB2ENR|= 0xFC;
	remoto_init();
   while (1)
      ;
 }   
